from datetime import datetime

from excel_etl.executions.transformation.project import ProjectTransformation
from excel_etl.executions.transformation.resource import ResourceTransformation

DEFAULT_CONNECTION_STRING = "postgres://postgres:postgres@localhost:5432/postgres"

PROJECTS = "comp_projects"
BUILDINGS = "comp_buildings"
APPS = "comp_apps"
USERS = "comp_users"
ENTREPRENEURS = "comp_entrepreneurs"
CONTRACTORS = "comp_contractors"
IMAGES_2D = "comp_2d_imgs"

TRANSFORMATIONS = {
    PROJECTS: ProjectTransformation,
    IMAGES_2D: ResourceTransformation

}
PROCESS_TABLES_SCHEMA = {
    "comp_proj_workers_relations": ["type", "proj_id", "worker_id"]
}

TABLES_SCHEMA_TYPES = {
    'comp_projects': {'proj_id': int,
                      'proj_status': str,
                      'proj_type': str,
                      'proj_pop_date': datetime,
                      'proj_description': str,
                      'proj_area': str,
                      'proj_loc_data_pg': str,
                      'proj_loc_data_google': dict,
                      'proj_loc_close_places_google': dict,
                      'proj_address': str,
                      'proj_rating': str,
                      'proj_url': str,
                      'proj_extension_fields': dict,
                      'proj_add_date': datetime,
                      'proj_update_date': datetime,
                      'proj_entrepreneur_ids': str,
                      'proj_contractor_ids': str,
                      'proj_update_version': str,
                      'proj_contact_details': dict},
    'comp_buildings': {'build_id': int,
                       'build_number': str,
                       'build_proj_id': int,
                       'build_status': str,
                       'build_floors': str,
                       'build_address': str,
                       'build_description': str,
                       'build_extension_fields': dict,
                       'build_pop_date': datetime,
                       'build_update_date': datetime,
                       'build_update_version': int},
    'comp_apps': {'app_id': int,
                  'app_build_id': int,
                  'app_number': int,
                  'app_floor': str,
                  'app_type': str,
                  'app_proj_id': int,
                  'app_porch': str,
                  'app_porch_area': str,
                  'app_area': str,
                  'app_price': int,
                  'app_promotion': str,
                  'app_promotion_expire_date': datetime,
                  'app_status': str,
                  'app_description': str,
                  'app_extension_fields': dict,
                  'app_rooms': str,
                  'app_pop_date': datetime,
                  'app_update_date': datetime,
                  'app_parking': bool,
                  'app_directions': str,
                  'app_update_version': int},
    'comp_users': {'user_id': int,
                   'user_name': str,
                   'user_contact_details': dict,
                   'user_email': str,
                   'user_password': str,
                   'user_add_date': datetime,
                   'user_update_date': datetime,
                   'user_update_version': int,
                   'user_extension_fields': dict,
                   'user_role': str},
    'comp_entrepreneurs': {'ent_id': int,
                           'ent_description': str,
                           'ent_ratings': str,
                           'ent_name': str,
                           'ent_web_site': str,
                           'ent_contact_details': dict,
                           'ent_extension_fields': dict,
                           'ent_update_version': int,
                           'ent_add_date': datetime,
                           'ent_update_date': datetime},
    'comp_contractors': {'cont_id': int,
                         'cont_name': str,
                         'cont_web_site': str,
                         'cont_contact_details': dict,
                         'cont_type': str,
                         'cont_extension_fields': dict,
                         'cont_ratings': str,
                         'cont_update_version': int,
                         'cont_add_date': datetime,
                         'cont_update_date': datetime},
    'comp_2d_imgs': {'img_id': int,
                     'img_class': str,
                     'img_file_url': str,
                     'img_type': str,
                     'img_dimensions': str,
                     'img_extension_fields': dict,
                     'img_source_id': int,
                     'img_source_type': str,
                     'img_add_date': datetime,
                     'img_update_date': datetime},
    'comp_3d_obj': {'obj_id': int,
                    'obj_class': str,
                    'obj_file_url': str,
                    'obj_type': str,
                    'obj_extension_fields': dict,
                    'obj_add_date': datetime,
                    'obj_validate_date': datetime,
                    'obj_source_id': int,
                    'obj_source_type': str},
    'comp_videos': {'video_id': int,
                    'video_size': str,
                    'video_type': str,
                    'videos_source_id': int,
                    'videos_source_type': str,
                    'video_add_date': datetime,
                    'video_update_date': datetime,
                    'videos_file_url': str,
                    'video_extension_fields': dict}}
